collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3335123
color:
  saturation: 0.3603652
  brandStrength: 0.1098231
  rhythmicContrast: 0.9057896
  brandColors:
    - '#FFFFFF'
    - '#B8B9BB'
    - '#030303'
    - '#A8196B'
    - '#5E4C45'
  lightness: 0.5592403
layout_spectrum: 0.3464017
name: Allpa
